name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  ci:
    uses: ybendris/github-workflows/.github/workflows/maven-ci.yml@0.1.0
    with:
      java-version: "25"